<?php

namespace AppBundle\Repository;

/**
 * ExempleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExempleRepository extends \Doctrine\ORM\EntityRepository
{
}
