<?php

namespace AppBundle\Repository;

/**
 * Strategy_ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Strategy_ContentRepository extends \Doctrine\ORM\EntityRepository
{
}
